### ISSUE TITLE
FirebaseResponse - OnAsync

### ISSUE THREAD

**Issue by bhdebrito** [ziyasal/FireSharp#10]
Hi again!

Now I'm using OnAsync to watch a path. The event handler are sending property by property, why just not send entire object? 

Maybe create a T method that convert the Json response to a complex object?

In this case I'm with some problems to undestand all the context to change that, so I'll have some dificulties to create a pull request.

**Comment by ziyasal** [comment]
Hi @bhdebrito I'll take a look asap.

**Comment by bhdebrito** [comment]
That's ok now!

On last release there is a GetAsync and OnChangeGetAsync
