### ISSUE TITLE
Serializer specified in FirebaseConfig not used when calling the object extension ReadAs

### ISSUE THREAD

**Issue by timblackwell** [ziyasal/FireSharp#15]
When using custom serializer passed in through the FirebaseConfig, you would expect the object extension ReadAs to use that ISerializer however it uses a new JsonNetSerializer object to deserialize.

Can this behaviour be changed?

**Comment by ziyasal** [comment]
@timblackwell Thank you for your feedback; to fix this temporarily use following code; 
```csharp
ObjectExtensions.Serializer = yourSerializerInstance
```

**Comment by timblackwell** [comment]
Thanks, this works perfectly for me.
