### ISSUE TITLE
OnAsync incorrect if multiple children exist

### ISSUE THREAD

**Issue by larsvi** [ziyasal/FireSharp#16]
UPDATE: It would seem that the following line in TemporaryCache.UpdateChildren solves the problem. Please verify and incorporate into source code if correct..

```
case JsonToken.EndObject: return;
```

END UPDATE.

Start with a Firebase where multiple children already exist:
{
  "todos" : {
    "push" : {
      "-Jq6BpBSCa3zmrWVSIj8" : {
        "name" : "Execute PUSH",
        "priority" : 2
      },
      "-Jq6CBIN1B0Xx5X0rzbJ" : {
        "name" : "Execute PUSH",
        "priority" : 2
      },
      "-Jq6CG_MtbJDssasD2jp" : {
        "name" : "Execute PUSH",
        "priority" : 2
      }
    }
  }
}

When connecting OnAsync to a Firebase where multiple children already exist, Notifications coming back to the Added event handler are incorrect.

Example: 
JSON initially streamed from Firebase upon connection:
{
    "path":"/",
    "data":{
        "-Jq6BpBSCa3zmrWVSIj8":{"name":"Execute PUSH","priority":2},
        "-Jq6CBIN1B0Xx5X0rzbJ":{"name":"Execute PUSH","priority":2},
        "-Jq6CG_MtbJDssasD2jp":{"name":"Execute PUSH","priority":2}
    }
}

Expected at Added:
/-Jq6BpBSCa3zmrWVSIj8/name, Execute PUSH
/-Jq6BpBSCa3zmrWVSIj8/priority, 2
/-Jq6CBIN1B0Xx5X0rzbJ/name, Execute PUSH
/-Jq6CBIN1B0Xx5X0rzbJ/priority, 2
/-Jq6CG_MtbJDssasD2jp/name, Execute PUSH
/-Jq6CG_MtbJDssasD2jp/priority, 2

Actually received at Added:
/-Jq6BpBSCa3zmrWVSIj8/name, Execute PUSH
/-Jq6BpBSCa3zmrWVSIj8/priority, 2
/-Jq6BpBSCa3zmrWVSIj8/-Jq6CBIN1B0Xx5X0rzbJ/name, Execute PUSH
/-Jq6BpBSCa3zmrWVSIj8/-Jq6CBIN1B0Xx5X0rzbJ/priority, 2
/-Jq6BpBSCa3zmrWVSIj8/-Jq6CBIN1B0Xx5X0rzbJ/-Jq6CG_MtbJDssasD2jp/name, Execute PUSH
/-Jq6BpBSCa3zmrWVSIj8/-Jq6CBIN1B0Xx5X0rzbJ/-Jq6CG_MtbJDssasD2jp/priority, 2

I have traced the problem down to TemporaryCache.UpdateChildren - my guess is the switch on JsonToken ignores JsonToken.EndObject where it needs to go up the tree one level. 
However I do not know this code well enough to confidently propose a solution.

Thanks,
Lars

**Comment by mjk0104** [comment]
Thanks for this fix Lars, saved me a lot of headaches.

Can this be pulled into the main branch? It's seems like some fairly core functionality to be broken...

**Comment by MrWolfZ** [comment]
I would be interested in seeing this fix in the main branch as well.

**Comment by ArildBelsvik** [comment]
This is still a problem in version 2.0.3 of FireSharp

**Comment by bezysoftware** [comment]
Still broken. Can we please have this merged?

**Comment by arcosmin** [comment]
assume fixed since the merge happen just no one closed the issue

**Comment by deebash** [comment]
How to build FireSharp.dll after fixing this issue. When i build solution, I'm getting FireSharp.core.dll which lacks many functionalities.
