### ISSUE TITLE
Cancel OnAsync()

### ISSUE THREAD

**Issue by ThomasCle** [ziyasal/FireSharp#25]
I am using the "OnAsync" method. Is there a way to stop the listening for events? In my case the user can disable the tracking of changes and then I would like to cancel the OnAsync.

There is a cancel implemented internally, but it is not implemented to client.

Thanks.

**Comment by ziyasal** [comment]
@ThomasCle Thanks for your feedback, you can stop listening for events by calling [EventStreamResponse](https://github.com/ziyasal/FireSharp/blob/master/FireSharp/Response/EventStreamResponse.cs)'s [Dispose](https://github.com/ziyasal/FireSharp/blob/master/FireSharp/Response/EventStreamResponse.cs#L134) method.  Here is sample code;

```csharp
 EventStreamResponse response = await _client.OnAsync("chat",
                added: (sender, args) => { System.Console.WriteLine(args.Data + " -> 2\n"); },
                changed: (sender, args) => { System.Console.WriteLine(args.Data); },
                removed: (sender, args) => { System.Console.WriteLine(args.Path); });

//Call dispose to stop listening for events
response.Dispose();
```

**Comment by krishnendra1987** [comment]
Hello ziya .can you please let me know how to continously get data from firebase database into xamrin.ios. I managed to get data by using firebaseclient.get() method but if any new data comes into database how can we get without refreshing .
