### ISSUE TITLE
Support streaming gets and produce events for item added, updated, and removed

### ISSUE THREAD

**Issue by ziyasal** [ziyasal/FireSharp#4]

**Comment by sundaywork** [comment]
how to attach events monitor for data change?

**Comment by ziyasal** [comment]
Hi @sundaywork;

To minitor data change, simply;
```csharp
IFirebaseConfig config = new FirebaseConfig
            {
                AuthSecret = FIREBASE_SECRET,
                BasePath = 
  _client = new FirebaseClient(config)
 await _client.ListenAsync("chat", (sender, args) => { System.Console.WriteLine(args.Data); });
```
For running [sample](https://github.com/ziyasal/FireSharp/blob/master/FireSharp.Test.Console/Program.cs)

**Comment by ziyasal** [comment]
Added with [f61e2f8](https://github.com/ziyasal/FireSharp/commit/fa74598bd4d0859cdffbee2486a505f1ff359bd5)
