### ISSUE TITLE
Incompatible with .Net Core

### ISSUE THREAD

**Issue by doczoidberg** [ziyasal/FireSharp#56]
`Package FireSharp 2.0.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package FireSharp 2.0.4`

Will there be compatiblity with the new .Net core?

**Comment by himadrinath** [comment]
@ziyasal **when it well be available for .net core 1.0 ..........**

**Comment by dcworldwide** [comment]
This will be huge for my company! Please advise if .net core support is in the works 👍

**Comment by dcworldwide** [comment]
What is actually involved in porting to .net core? Is it a huge amount of work?

**Comment by ziyasal** [comment]
Hey @all it is actually in my road map but I am so busy nowadays both personal life and job side. So, It might be delay to make it available.
Thank you!

**Comment by ubirajaramnj** [comment]
Hi ziyasal,

can I contribute make it compatible with .Net Core?

**Comment by sandcastle** [comment]
@ziyasal any update on others providing help or your ETA to update?

**Comment by ziyasal** [comment]
hi @all It would be good to see that someone working on this, IMO it shouldn't be huge amount of work but I haven't find a time to work on.

**Comment by jazpearson** [comment]
I've just submitted a PR for this (#76).
There's a bit of work to do to tidy it up, but it should be a pretty good start. Converting the firesharp project was very simple. The unit tests are what took most of the time (and there's 1 failing).

**Comment by jviaches** [comment]
Support for .NET Core would be great :)

**Comment by doczoidberg** [comment]
works with .NET Core 2.0!

**Comment by ziyasal** [comment]
:+1: cool!

**Comment by himadrinath** [comment]
**NuGet not updated yet.....................**

**Comment by doczoidberg** [comment]
you need .NET core 2.0. It supports more libraries than 1.1

**Comment by himadrinath** [comment]
i already have 2.0

**Comment by doczoidberg** [comment]
it should work with the nuget package
