### ISSUE TITLE
Confusion over BasePath field

### ISSUE THREAD

**Issue by lordplagus02** [ziyasal/FireSharp#57]
I'm not sure what is actually required to configure this library because I don't see anything about BasePath on [these Google docs](https://firebase.google.com/docs/cloud-messaging/downstream).

I think perhaps this is part of an old version of firebase?

**Comment by Skeldave** [comment]
1. Log into your the firebase.google.com 
2. Select your app
3. Click 'Database' in the side bar.
4. You should see a URL at the top of the page which is something like: 
https://APP_NAME-3bb2a.firebaseio.com/

This is your BasePath
