### ISSUE TITLE
How to calculate the total records in the tables

### ISSUE THREAD

**Issue by ntdatgoquovn** [ziyasal/FireSharp#59]
Dear author,

Please let me know. How to calculate the total records in the database.
I want to use it to paging

Thank you very much.

**Comment by argcos** [comment]
Not by default, Firebase doesn't provide it. You would need to load all the data or save and maintain a counter on the database. The workaround for pagination would be
```C#
var start = 0;
var end = 10;

var response = await _client.GetAsync("path", QueryBuilder.New().OrderBy("field_name").StartAt(start.ToString()).EndAt(end.ToString()));
var result = response.ResultAs<List<TestClass>>();  
```
