### ISSUE TITLE
Failed to validate MAC

### ISSUE THREAD

**Issue by achabill** [ziyasal/FireSharp#70]
UWP
Using: `var firebaseConfig = new FirebaseConfig { AuthSecret = id_token, BasePath = FirebaseBaseURL }` and calling  `PutAsync()` throws exception with Message : _"Failed to validate MAC"_  

id_token:
`"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3NpbXBsZXNvY2lhbG1lZGlhLmF1dGgwLmNvbS8iLCJzdWIiOiJmYWNlYm9va3wxMzkyNTM5Nzk3NDQyODcwIiwiYXVkIjoiVldqU1hvOUY0eFBMbEFtMktNeXJMb0s4bVd3c2hYYjQiLCJleHAiOjE0NzMyMDQ0NzQsImlhdCI6MTQ3MzE2ODQ3NCwidiI6MCwiZCI6eyJmYl9pZCI6ImZhY2Vib29rfDEzOTI1Mzk3OTc0NDI4NzAifSwiYXpwIjoiVldqU1hvOUY0eFBMbEFtMktNeXJMb0s4bVd3c2hYYjQifQ.2fsK1YWNycT3iJvFncprEcoUNr2WIEwz9ZCKFHYTFOg"`  

Gotten from Auth0: `auth0.GetDelegationToken()`

What is wrong?

**Comment by argcos** [comment]
You need the Database Secret from Project Settings -> Service Accounts -> Database Secrets

![image](https://cloud.githubusercontent.com/assets/6182380/23331038/72c8de2a-fb55-11e6-86ec-f3b374634417.png)
