### ISSUE TITLE
How to limit the number of items to display

### ISSUE THREAD

**Issue by pooran** [ziyasal/FireSharp#75]
We need only 2 last updated items from thousands of items. is there a way I can filter the same from GET / GETALL ?

**Comment by doreto** [comment]
I'm looking for solution too, but for  _client.OnAsync method.

**Comment by aupp** [comment]
You could use the QueryBuilder and the "LimitToFirst"-method. Or you could put together your own query and just pass it to QueryBuilder.New("your-query") and use it in the Get method.

**Comment by TiagoGouvea** [comment]
I'm looking a solution to use with OnAsync too... 
@aupp can your solution work with?

**Comment by arcosmin** [comment]
assume no help required anymore
