### ISSUE TITLE
Querybuilder NotFound response

### ISSUE THREAD

**Issue by Sagariouz** [ziyasal/FireSharp#82]
Hi guys.

I'm trying the new QueryBuilder to limit the amount of data that is fetched, but I'm getting an exception on the request:
"Request responded with status code=NotFound, response=not found"

`FirebaseResponse response = await client.GetAsync("Routes", QueryBuilder.New().LimitToFirst(8));`
It works without the QueryBuilder param.

I'm not using Auth and I havent upgraded to the new dashboard yet, may that be the issue?

**Comment by Sagariouz** [comment]
If anyone else gets this exception. I needed to add some form of authentication on the client call.

Thx for this added feature, saved me..

**Comment by TiagoGouvea** [comment]
When I call ````QueryBuilder.New().LimitToLast(10)````  It give me **"orderBy must be defined when other query parameters are defined"**

**Comment by arcosmin** [comment]
@TiagoGouvea you need to order your objects by something to use limit to last since there is know default ordering on the firebase db
