### ISSUE TITLE
CreateUser

### ISSUE THREAD

**Issue by malohr** [ziyasal/FireSharp#85]
Hi,

I tried to create a user via email and pw, but unfortunately it doesn't work.
Here is my method 

public partial class SignUp : ContentPage
	{

		private const string BasePath = "my url to the database";
		private const string FirebaseSecret = "API key is here";
		private static FirebaseClient _client;
		private String email;
		private String password;

		public SignUp()
		{
			InitializeComponent();

			IFirebaseConfig config = new FirebaseConfig
			{
				AuthSecret = FirebaseSecret,
				BasePath = BasePath
			};

			_client = new FirebaseClient(config);
		}

		public async void Submit(object sender, EventArgs e)
		{
			email = UsernameEntry.Text;
			password = PasswordEntry.Text;
			_client.CreateUser(email, password);

		}

**Comment by EdersF** [comment]
I have the same problem :/

**Comment by argcos** [comment]
Have you enabled the email/password authentication?

![image](https://cloud.githubusercontent.com/assets/6182380/23334135/ab491a54-fb90-11e6-85e2-bd6453838642.png)

Also, I assume you are using the correct secret. FireSharp uses a deprecated method, you can find this secret under Cog (top left) -> Project Settings -> Service Accounts -> Database Secrets.

If these don't fix it, can you post the response you are getting back?

**Comment by arcosmin** [comment]
No reply assumed resolved
