### ISSUE TITLE
VB.NET

### ISSUE THREAD

**Issue by CarterMiller** [ziyasal/FireSharp#86]
The library looks great, and appears to suggest that I should be able to use it with VB.NET - but I can't find any examples anywhere, and translating the javascript examples isn't working.

**Should** I be able to use this library with VB.NET (Visual Studio 2015), and if so, are there any examples to show how to get things started?

Russell

I found a splendid code translator [http://www.carlosag.net/tools/codetranslator/](url) which has solved this completely.  I would delete this issue is I was able to!

**Comment by amalg** [comment]
Mind posting some of that sweet translated example code for vb.net?

**Comment by mesut25** [comment]
yes. yes yes

> Vb.net için bu tatlı çevrilmiş örnek koddan bazılarını yayınlamak ister misiniz?

yes, yes, yes, yes,🖒😁
