### ISSUE TITLE
Async Methods

### ISSUE THREAD

**Issue by bhdebrito** [ziyasal/FireSharp#9]
Hi,

Why all methods now are async? 

Sometimes we don't need/want to call it in async context, now we are creating Task to do the job.

A solution that I propose is create two FirebaseClient, one async another sync.

I will do that and create a pull request.

**Comment by ziyasal** [comment]
Hi @bhdebrito 
Asynchronous call support as non-blocking io matters a lot nowadays. 

Also, There is [an article here](http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx) related this.

**Comment by ThumbDog** [comment]
I would like to have the non-async calls just for the sake of "debugging" as I find debugging async calls somewhat tedious. I'm still searching for a good strategy on this. btw - great job on this project @ziyasal !!!

**Comment by bhdebrito** [comment]
@ziyasal I understand that matters a lot, but we are upgrading from 1.10 version, now we are troubleshoot with last implementation.

I read the article, but why just not give the power of choice to us? I believe that when this project grow up, another programmers will want this!

@ThumbDog This project is awesome! I believe that will grow up with Firebase!

**Comment by ziyasal** [comment]
@ThumbDog and @bhdebrito  thanks for your comments. I'll take a look to bring back asap so if you already working on please let me know.

Thanks.

**Comment by bhdebrito** [comment]
@ziyasal I'm working! Let this with me!

**Comment by bhdebrito** [comment]
There are same sync methods for all async methods!
