### ISSUE TITLE
Nodes MAnage

### ISSUE THREAD

**Issue by jordinola** [ziyasal/FireSharp#93]
Hi, I would like to know if there is any way to handle the nodes that are created when you push an objec? There is the autogenerated key but I need to change that key for a custom value.

Thxs in advance

**Comment by argcos** [comment]
You will need to use set instead of push. And provide the custom key value in the url. If Firebase can't resolve it, it will be created.

```C#
var test = new TestClass()
            {
                Id = "random_string",
                Name = "Test",
                Surname = "Test"
            };

SetResponse response = await _client.SetAsync($"/{test.Id}", test);
TestClass result = response.ResultAs<TestClass>();
```
