### ISSUE TITLE
Get item key from list

### ISSUE THREAD

**Issue by roberzyx** [ziyasal/FireSharp#99]
Hi,
I'm trying to get the data from an array in the database and binding it to a ListBox using a custom class. I do it like this and I have no trouble doing it:
![image](https://cloud.githubusercontent.com/assets/28893010/26399341/e01a6586-407c-11e7-9fff-b20476ee9b61.png)
The problem comes when detecting a selection change in the ListBox, I don't know what item are they clicking at. It would be necessary to add to my class the key each one of the items retrieved by the response.

Any idea about how could I achieve this?
Thanks for awesome your work!

**Comment by argcos** [comment]
You should deserialize your data into a dictionary rather than a list where the key is the object id. Firebase stores key-value pairs so you should work with the data in the same way in your code.

**Comment by arcosmin** [comment]
Assume fixed
